### ISSUE TITLE
最新版有bug，会默认请求一个不存在的文件

### ISSUE THREAD

**Issue by xiyuvi** [Rock-Candy-Tea/hexo-webpushr-notification#6]
大佬，我又来了0.0这是最新版的请求
![111](https://user-images.githubusercontent.com/38217058/210054672-1705d2be-4c1d-476f-8b11-2408e7773457.jpg)
![222](https://user-images.githubusercontent.com/38217058/210054677-2a96b319-c3f6-4c2c-9908-bc7b9c168189.jpg)
我回退到0.0.14版本这个问题就消失了，烦请您有时间修复一下，看能不能给不需要自定义ws的人一个关闭的配置项

**Comment by CCKNBC** [comment]
麻烦升级到0.1.1版本，并注意配置变化
```yaml
webpushr:
  enable: true
  sw_self: false
```
